[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_escrow = "5q5k6oS5j3M7MJQg6YHLuJcK7nMzqBeDmJs9bMAerj3Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
