[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "22o7oMyfpW7vdGcPvzCc779NKuVUnpZTXrHRmhuvfb7B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
